### ISSUE TITLE
How to run android app on lollipop version 5.1

### ISSUE THREAD

**Issue by ankitjaiinn** [googlemaps/transport-tracker#20]
I am not able to run the android app on v5.1 

I have updated the minSdkVersion  to 22 in build.gradle in app folder. The app build successfully but getting an error in emulator as "Unfortunately, Transport Tracker has stopped."

**Comment by stephenmcd** [comment]
You'll need to provide the stack trace + error that should appear in Android Studio when running via there.

**Comment by gitcostan** [comment]
hi i got the same error on v5.1 and v4.4. The issue seems to be with the use of method isIgnoringBatteryOptimizations 

i have attached the stack trace as image.
pls advise the code change.
![error-4 4](https://user-images.githubusercontent.com/30388993/28817444-e1733bf4-76c5-11e7-9e2d-9b5c48bcaf88.png)

**Comment by domesticmouse** [comment]
Closing this out as old. Please re-open with stack trace.
