### ISSUE TITLE
Admin page not loaded

### ISSUE THREAD

**Issue by rpputra** [googlemaps/transport-tracker#66]
Hi, please help, I setup everything good, but when I try to run admin page, it unable to load. Errors found in the browser developer console as below.
![image](https://user-images.githubusercontent.com/36644595/64682527-d0421a80-d4ab-11e9-8f62-324797910c29.png)

**Comment by rpputra** [comment]
apparently its not an error, its just waiting the android app tracking feature activated.

**Comment by chitgoks** [comment]
It is an error. This needs to be re-opened.

The android app somehow becomes unusable because one cannot run the app without providing a transport id, which is only viewable in the admin page.

The instructions are also vague to begin with.
It does not specifically say where to create the admin folder in. inside the transport-tracker-map folder (i guess this is the only viable location)?
and if so, it still gives out that error message.

I have successfully deployed the backend and maps project in firebase, but there are no instructions there for the admin page. on how to set it up. just instructions to add api keys. but it does not work.
